### ISSUE TITLE
Can not compile

### ISSUE THREAD

**Issue by hnagoya** [neubig/webigator#1]
はじめまして。neubig-webigator-f8fc516.tar.gz を展開しますと autoreconf -i の段階で
src/include/webigator/config.h.in: No such file or directory
とエラーになるのですが neubig さんのお手元ではどこかに webigator/config.h があって、github へアップロードされていないということはないでしょうか。

**Comment by neubig** [comment]
失礼しました！gitの.gitignoreファイルでミスしてしまって、必要なファイルの一部がアップされていませんでした。最新版に更新していただければコンパイルできるようになると思います。

**Comment by hnagoya** [comment]
neubig-webigator-535a9d7 を Ubuntu 12.04 LTS Desktop 上で README にしたがい make したところ下記のようなエラーで先に進めないのですが、アドバイスいただければ幸いです。

make[2]: Entering directory `/tmp/neubig-webigator-535a9d7/src/lib'
/bin/bash ../../libtool --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../../src/include/webigator  -I./../include   -g -O2 -MT webigator-server.lo -MD -MP -MF .deps/webigator-server.Tpo -c -o webigator-server.lo webigator-server.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../src/include/webigator -I./../include -g -O2 -MT webigator-server.lo -MD -MP -MF .deps/webigator-server.Tpo -c webigator-server.cc  -fPIC -DPIC -o .libs/webigator-server.o
webigator-server.cc: In member function 'virtual void BestPopper::execute(const xmlrpc_c::paramList&, xmlrpc_c::value*)':
webigator-server.cc:149:13: error: 'generateResponse' is not a member of 'xmlrpc_c::xml'
make[2]: *** [webigator-server.lo] Error 1
make[2]: Leaving directory`/tmp/neubig-webigator-535a9d7/src/lib'
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory `/tmp/neubig-webigator-535a9d7/src'
make: **\* [all-recursive] Error 1

**Comment by neubig** [comment]
こちらでバグを再現できませんでした（おそらくxmlrpc-cのバージョンの違い）が、generateResponseはデバッグメッセージをプリントするために使っていただけですので、消しておきました。申し訳ないですが、もう一度最新版でコンパイルを試していただけませんか？

**Comment by hnagoya** [comment]
アドバイスありがとうございました neubig さん

neubig-webigator-33c6c1a.tar.gz
Ubuntu 12.04 LTS Desktop

で README の記述にしたがい make 後に src/bin/webigator が起動するところまで進みました。

**Comment by neubig** [comment]
良かったです！ご報告ありがとうございました。
